name: Generate Snake Animation

on:
  schedule:
    # Roda a cada 12 horas
    - cron: "0 */12 * * *" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: generate github-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            output/github-contribution-grid-snake.svg
            output/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # ⬇️ NOVO PASSO ADICIONADO PARA COMMITAR O ARQUIVO SVG ⬇️
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat: Atualiza gráfico Snake Game"
          file_pattern: output/*.svg
