name: Update Pacman Graph

on:
  schedule:
    # Roda a cada 1 hora
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pacman Contribution Graph Action
        uses: pacman-dots/pacman-contribution-graph@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_path: output/pacman-contribution-graph
